version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "09:00"
    open-pull-requests-limit: 10