name: FromDoppler

on:
  push:
    branches: ["main", "INT"]
    tags:
      - v*.*.*
  pull_request:
    branches: ["main"]

jobs:
  dotnet:
    name: .NET
    uses: FromDoppler/.github/.github/workflows/dotnet.yml@main
  docker:
    if: ${{ github.event_name == 'push' }}
    name: Docker
    uses: FromDoppler/.github/.github/workflows/continuous-delivery-dockerfile.yml@main
    secrets: inherit
    with:
      dockerfile-path: "Doppler.ImageAnalyzer.Api/Dockerfile"
      dockerhub-image-name: "doppler-image-analyzer"
